### ISSUE TITLE
images

### ISSUE THREAD

**Issue by iamdobi** [alicek106/start-docker-kubernetes#1]
-

**Comment by alicek106** [comment]
안녕하세요. 어떤 이유로 이슈를 open하셨는지 description을 추가해주시면 좋겠습니다.

**Comment by iamdobi** [comment]
앗!!! 
죄송합니다! 여기에 올릴 것이 아닌데 정신이 없어서 이곳에 올렸네요 ㅠㅠ 죄송합니다.

(사내에서 해당 교재로 스터디를 하고 있고, 스터디 자료 준비 중이었는데, 사내 github인줄 알았습니다.. OTL)
