### ISSUE TITLE
CertificateSigningRequest의 yaml인 chapter10/alicek106-csr.yaml에서 오류 발생

### ISSUE THREAD

**Issue by zzozzolev** [alicek106/start-docker-kubernetes#12]
안녕하세요.
github에 있는 파일로 실습하던 중 해당 리소스를 만드는 yaml에서 오류가 나서 이슈를 올렸습니다.

### 에러
- `apiVersion`이 맞지 않아 다음의 에러가 발생합니다.
https://github.com/alicek106/start-docker-kubernetes/blob/9ec196a0937667fff43d05926bac2cafea3cd874/chapter10/alicek106-csr.yaml#L1
```
error: unable to recognize "alicek106-csr.yaml": no matches for kind "CertificateSigningRequest" in version "certificates.k8s.io/v1beta1"
```
### 해결
- `apiVersion: certificates.k8s.io/v1`으로 변경시 해결됩니다.

### 에러
- required field인 `singerName`이 없어 다음의 에러가 발생합니다. [공식 문서](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#request-signing-process)에 " Note that spec.signerName is a required key after API version certificates.k8s.io/v1" 라고 나와있습니다.
```
error: error validating "alicek106-csr.yaml": error validating data: ValidationError(CertificateSigningRequest.spec): missing required field "signerName" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
### 해결
- `signerName: kubernetes.io/kube-apiserver-client`을 추가하면 해결됩니다.
- 여러 [singerName](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers)이 있는데, 위의 `singerName`을 쓰는 게 맞는지 확신은 못하겠습니다.

교재를 통해 쿠버네티스에 대해 잘 배우고 있습니다. 🙂
감사합니다.

**Comment by alicek106** [comment]
안녕하세요, 해당 부분은 책이 쿠버네티스 구 버전을 기준으로 설명하고 있기 때문에 발생한 문제로 보이며, 최신 개정판에서는 수정되어 발간될 예정입니다.

다른 독자분들께서 동일한 내용으로 헷갈리시지 않도록 리포지터리의 내용에 추가 설명을 달아둘 예정이며, 금주 주말에 수정할 예정입니다.

제보해주셔서 진심으로 감사드립니다!

**Comment by alicek106** [comment]
https://github.com/alicek106/start-docker-kubernetes/commit/85aa5d0b098f3c1036e8e8ac214d869b8cddc2a5 에서 수정되었습니다. 좋은 주말 되시길 바라겠습니다.
