### ISSUE TITLE
[책 p.29] Docker Desktop for Mac 사용 시, 컨테이너를 외부에 노출할 때 질문입니다

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#14]
안녕하세요? 출판해주신 책을 통해 도커와 쿠버네티스를 입문하고 있는 사람입니다. 우선 좋은 책을 출간해주셔서 감사인사부터 드립니다. 다름이 아니라 책으로 공부하다가 궁금한 점이 생겨 질문드립니다!

우선 책 29페이지의 하단 주석에 보면 Docker Desktop for Mac 도커 엔진을 이용하면 로컬 호스트에서 컨테이너 IP로 접근이 불가능하다고 적어주셨는데요? 제가 이전에 도커를 잠깐 얕게(?) 공부할 적엔 Docker Desktop for Mac 도커 엔진을 사용했었는데, 그 때 당시에 포트 포워딩 기능(`-p` 옵션)을 활용해 로컬 호스트와 컨테이너 포트를 연결하고, 볼륨 기능(`-v`)을 활용해 로컬 호스트와 컨테이너의 파일 시스템을 연결했을 때는 로컬 호스트에서 컨테이너 IP에 접근이 가능했는데요? 

그러면 주석에 써주신 것처럼 "Docker Desktop for Mac 도커 엔진을 이용하면 로컬 호스트에서 컨테이너 IP로 접근이 불가능하다" 라는 것은 포트 포워딩 기능(`-p` 옵션)만 사용했을 때는 불가능하지만, 볼륨 기능(`-v` 옵션)을 활용하면 가능해진다로 이해하면 될까요!? 다시 말해, 볼륨 이라는 기능이 Docker Desktop for Mac 도커 엔진에서 로컬 호스트에서 컨테이너 IP로 접근을 가능하게 해주는 것인지 궁금합니다!

답변 천천히 달아주셔도 좋습니다. 기다리고 있겠습니다. 감사합니다 :)

**Comment by iamcodingcat** [comment]
@alicek106 저자님! 바쁘실텐데.. 시간이 나신다면 위에 답변 꼭 부탁드립니다. ( __ )

**Comment by alicek106** [comment]
죄송합니다, 알람이 묻혀서 미처 확인하지 못했네요. 최대한 빨리 확인해서 답변드리겠습니다.

**Comment by alicek106** [comment]
지금 바로 테스트해보았는데, 볼륨과는 상관 없이 컨테이너 IP에 접근이 불가능한 것으로 확인되었습니다. Docker Desktop에서는 기본적으로 VM 내부에서 컨테이너를 생성하며, 로컬 호스트에서 해당 VM 내부로 향하는 라우팅이 잡혀있지 않는 한 (혹은 별도의 SOCK 프록시 설정이 Docker Desktop에 설정되어 있지 않은 한) 컨테이너 IP로 직접 통신하는 것은 불가능한 것으로 알고 있는데요.

질문자님께서 컨테이너 IP로 통신하는 것에 성공하셨다는 환경을 정확하게 설명해주실 수 있을까요? 가능하다면 재현 가능하도록 한 번 더 실험해보시면 가장 좋습니다.

**Comment by iamcodingcat** [comment]
@alicek106 오 이게 알람이 가는군요! 아닙니다! 빠른 답변 감사합니다! 

제가 이제야 볼륨에 대해서 책으로 배우고 있는데, 볼륨에 대한 개념을 잘 모르고 컨테이너 IP로 통신하는 것에 성공했다고 한 것 같아요!
볼륨은 단순히, 호스트와 컨테이너 간의 디렉토리(또는 파일)를 공유하는 것인데, 저는 이게 ``공유가 가능함 = 통신이 가능함`` 으로 저도 모르게 이렇게 해석한 것 같습니다! 그렇다면.. 정리를 하자면 "볼륨은 단지 데이터를 공유하는 것일 뿐 호스트와 컨테이너 간에 통신을 가능하게 하는 것은 아니다" 로 이해하면 될까요!?

그리고 한 가지 추가로 여쭙고 싶은 점이 있는데요! 책 40페이지에서 볼륨을 통해서 호스트의 /home/wordpress_db 디렉터리와 컨테이너의 /var/lib/mysql 디렉터리를 연결했는데요!? 그런데, 이 연결이 "두 개의 디렉터리를 동기화 하는 것이 아니라 완전히 같은 디렉터리"라고 설명해주셨는데요? `동기화` 와 `완전히 같은 디렉터리` 이 두 개 간의 차이점이 무엇인가요? 
예전에 실습했던 기억으로는... 예를 들어 호스트의 index.html 을 컨테이너로 볼륨을 통해 마운트했을 때, 호스트의 index.html 파일 내용을 수정하면 자동으로 index.html과 연결된 컨테이너 파일도 수정되는 걸로 기억을 하는데요! 그러면 이게 동기화는 아닌 걸까요!? 
제가 아직 도커에 입문 실력이라.. 설명이 다소 모호할 수 있습니다. 이해가 안가시는 부분 답글 달아주시면 다시 질문드리도록 하겠습니다!

**Comment by alicek106** [comment]
1. "볼륨은 단지 데이터를 공유하는 것일 뿐 호스트와 컨테이너 간에 통신을 가능하게 하는 것은 아니다" : 네 맞습니다. 적어도 제가 아는 선에서는 볼륨과 네트워크에서는 상관관계가 없습니다.

2. (리눅스를 기준으로 설명드리자면) 동기화는 A 디렉터리와 B 디렉터리 간의 내용을 완전히 똑같이 복사하는 것이라고 볼 수 있습니다. 하지만 A와 B에 각각 존재하는 파일들은 내용물만 같을 뿐, 파일을 구별하는 식별자 (e.g. inode 등) 은 다를 것입니다. 만약 동기화를 중단하면 A 또는 B 디렉터리에서 파일을 수정해도 A와 B 디렉터리의 파일에는 아무런 영향을 끼치지 않게 됩니다. 리눅스에서 디렉터리 동기화를 하는 방법에는 여러가지가 있는데요, rsync나 RAID 복제 등이 이에 해당합니다. 디렉터리 동기화에 관심이 있으시다면 rsync, RAID를 키워드로 찾아보시는 것을 추천드립니다,

도커 볼륨은 동기화가 아닌, 완전히 동일한 파일을 양쪽에 마운트하는 것입니다. 때문에 -v 옵션을 통해 공유된 파일의 고유한 식별자는 호스트와 컨테이너 양쪽에서 동일할 것입니다. 이게 가능한 이유는 리눅스의 마운트 네임스페이스 등을 통해 가능한 것인데요. 이 원리에 대해 자세히 설명하자면 너무 길어지기 때문에 직접 찾아보고 테스트해보시는 것을 추천드립니다. (참고로, 책의 내용은 도커를 처음 시작하시는 분을 위해 작성한 것이라서 여기까지 설명하지는 않고 있습니다)

좀 더 쉽게 설명하자면, 양쪽 디렉터리에 동일한 파일이 2개 존재하느냐, 아니면 완전하게 동일한 파일 하나만 존재하느냐 라고도 말할 수 있겠습니다.

**Comment by iamcodingcat** [comment]
@alicek106 와 자세한 설명 너무 감사드립니다! 동기화와 완전한 복사 차이가.. 이렇게 비유하면 될지 모르겠지만 프로그래밍 언어에서 얕은 복사와 깊은 복사같은 차이인 것 같네요 ㅎㅎ 명확히 이해가 되었습니다!

책 너무 잘 읽어 나가고 있습니다~ 제가 질문이 많아서.. 책 내용 학습하다가 또 궁금한 점 있으면 이슈에 남기도록 하겠습니다 ㅎㅎ 늦은 시간임에도 답변 주셔서 감사합니다! 좋은 밤 되세요~
