### ISSUE TITLE
[p.92] 이미지 삭제 시 질문

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#15]
@alicek106 
안녕하세요~ 책 여전히 잘 읽고 있습니다. 92쪽 [이미지 삭제] 챕터와 관련하여 한 가지 질문드리고 싶은 게 있는데요? 책에서 예시를 들어주신 것처럼 아래와 같이 3개의 컨테이너가 존재한다고 가정해볼게요!

<img width="150" alt="스크린샷 2023-03-19 오후 2 46 29" src="https://user-images.githubusercontent.com/54783194/226156211-16c593dc-b5b4-4eea-92e0-0df4d3023ebb.png">

책에서, image A, B를 각각 삭제할 때 경우를 들어주셔서 설명해주셨는데요? 제가 궁금한 부분은 image A를 삭제할 때인데요?
일단, image A를 삭제하기 위해서는 "image A를 부모로하는 image B(자식 이미지)가 존재하지 않아야 실질적인 삭제가 가능하다" 라고 하셨는데요? 그런데 여기에 추가로 image A를 삭제하기 위해서는 "image A의 부모 이미지인 ubuntu:14.04 이미지를 삭제해야 한다"는 조건도 만족해야 하는 거 아닌가요? 즉, 이 2가지 조건을 모두 만족(and 조건)해야 실질적으로 image A가 삭제되는 것인지, 둘 중 하나만 만족(or 조건)해도 삭제되는 것인지 궁금하네요!

이렇게 생각한 이유는 image B를 삭제할 때 붙는 조건 때문인데요? image B를 삭제할 때 "image B의 부모 이미지인 image A가 존재하지 않아야 한다" 라고 하셨는데요? 그렇다면 "image A" 입장에서는 image A의 부모 이미지가 ubuntu14.04 이미지이기 때문이라고 생각했는데요? 이에 대한 답변 가능하신지 문의드려요!

**Comment by alicek106** [comment]
이미지 A를 삭제하기 위해서는 ubuntu:14.04 이미지를 삭제하지 않아도 됩니다.

- 부모 이미지의 데이터(이미지 레이어)가 실제로 파일 시스템 상에서 삭제되기 위해서는 자식 이미지가 없어야 합니다.
- 위 그림에서는 B에 해당하는 자식 이미지를 삭제하기 위해서는 아무런 선결 조건이 없습니다.

책에서 설명드렸던 것처럼 이미지는 레이어 구조를 가지고 있다고 이해하시면 좀 더 이해가 쉬운데요. 하위 레이어는 상위 레이어에 종속성을 가지고 있기 때문에 leaf node가 아닌 이미지의 실제 데이터를 삭제하려면 그 하위 이미지들도 삭제되어야 합니다.

**Comment by alicek106** [comment]
그림으로 예시를 들어 설명해보겠습니다.

- 이미지 레이어 3를 사용하는 ubuntu 이미지가 존재함
- ubuntu 이미지를 기반으로 이미지 B를 생성함 (레이어 2에 해당)
- 이미지 B를 기반으로 이미지 A를 생성함 (레이어 1에 해당)

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/10753179/226487376-f3bfdd18-cb08-41a9-886a-790e0e91eb72.png">

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/10753179/226487391-1abf857b-8770-4095-aea0-258689e515d8.png">

**Comment by iamcodingcat** [comment]
@alicek106 친절하게 그림까지 그려주시다니 정말 감사합니다! 그림으로 이해하니 명확히 이해가 되었습니다. 알려주신 내용들 기반으로 책 잘 따라가보도록 하겠습니다 :)
