### ISSUE TITLE
[p.132] 멀티 스테이지 Dockerfile 빌드 실습 관련 질문

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#16]
@alicek106 
안녕하세요 멀티 스테이지 Dockerfile 빌드하는 실습 관련해서 질문이 있습니다! 제가 Go언어는 잘 몰라서.. 익숙한 python으로 책에서 해주신 것처럼 비슷하게 실습을 해보고 있는데요? 우선 멀티 스테이지 Dockerfile 과 표준출력 함수 파일은 아래와 같습니다!
```python
# main.py
def f():
    return "Hello world"
```

```Dockerfile
FROM python:3.10.1
ADD main.py /root
WORKDIR /root
RUN python main.py

FROM alpine:latest
WORKDIR /root/alpine
COPY --from=0 /root /root/alpine
CMD ["/bin/sh", "-c", "python /root/alpine/main.py"]
```

궁금한 점은 아래와 같은데요?

위 Dockerfile로 만든 이미지를 기반으로 컨테이너를 생성하면 해당 컨테이너 내부에 python 설치가 되어 있지 않다는 에러가 발생하면서 컨테이너가 생성되자마자 바로 종료(Exited)됩니다. 책에서 배운 내용에 의하면.. `--from=0` 가 첫번째 FROM에서 빌드된 이미지의 최종 상태를 의미하고, 이를 복사해서 두번째 이미지인 `alpine:latest` 에 그대로 붙여넣기 하게 되면 저는 당연히 `alpine:latest`에도 python이 내장 설치되어 있을거라고 생각했는데요? 왜냐하면 첫번째 FROM 이미지가 파이썬 이미지 이기 때문이라고 생각했습니다. 이게 아닌 건가요..? 아니면 `alpine:latest` 이미지에서 python 설치는 또 따로 해주어야 하는 건가요..? 제가 어떤 부분을 놓치고 있는건지.. 질문드립니다!

그리고 한 가지 추가적으로 제가 알아본 것은 위 Dockerfile로 만든 이미지를 기반으로 컨테이너를 생성하는데, `docker run` 명령어에 COMMAND 인자에 `/bin/sh` 로 overwrite를 해서 컨테이너 내부에 들어가보니 저 `main.py` 파일이 제가 원하는 `/root/alpine` 경로에 복사되어 있는 것은 확인했습니다. 다만, python이 설치되어 있지 않다보니 `python main.py` 명령어를 치면 역시 에러가 나네요...ㅠ

**Comment by iamcodingcat** [comment]
@alicek106 안녕하세요! 댓글 리마인드 죄송합니다만.. 시간 나실 때 한번 답변 부탁드려요!

**Comment by alicek106** [comment]
안녕하세요, 멀티 스테이지 빌드는 golang, c, c++, rust 등 컴파일을 통해 단일 바이너리를 빌드할 수 있는 언어들에서 자주 사용되는 패턴입니다. 컴파일러를 통해 빌드된 바이너리는 별도의 도구 없이도 기계어로서 바로 실행 가능하기 때문에 alpine와 같은 이미지에서도 바로 사용 가능하다고 이해하시면 됩니다.

파이썬은 컴파일러과 인터프리터 양쪽을 사용하는 언어로서, CPython에서는 pyc 등의 파일을 빌드한 뒤 인터프리팅을 수행하는 것으로 알고 있습니다. 다만 이 경우에도 pyc를 사용하기 위해서는 CPython이 설치되어 있어야 하기 때문에, 멀티 스테이지 빌드 패턴을 적용하기에는 적합하지 않습니다.

즉, 언어별 특성에 따라서 (컴파일 언어인지, 인터프리터 언어인지에 따라서) 멀티 스테이지 빌드 패턴을 적용할 수 있다는 점 참고 부탁드리겠습니다.

**Comment by iamcodingcat** [comment]
답변 감사합니다! 언어적인 특성이 이유일 줄은 몰랐네요. 도움이 되었습니다!
