### ISSUE TITLE
[p.190,191] 도커 스웜을 학습하기 위한 질문

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#17]
@alicek106 
안녕하세요! 책 잘 보고 있습니다. 제목에 작성한 것처럼 책 190,191 쪽에서 궁금한 점이 생겼는데요!? 도커 스웜 자체에 대한 질문은 아니고.. 책에서 도커 스웜이 필요한 이유를 설명해주시기 위해 작성하신 글을 읽다보니 문득 궁금한 점이 생겨 질문드립니다.

1. 서버 N대가 1개의 공통된 도커 엔진을 사용할 수 있는 건가요?
ㄴ 저는 그럴 수 있다고 생각하는데요? 배웠다시피 도커 엔진에는 도커 클라이언트/도커 데몬으로 구성되잖아요? 예를 들어, 서버 1,2,3,4가 있고 서버 1에서 도커 데몬이 실행되고 있다고 가정해볼게요. 그러면 서버 2,3,4는 Remote API를 사용해서 서버 1의 도커 데몬과 통신하게 된다면 결국 서버 N대가 1개의 공통된 도커 엔진(엄밀히 말하면 1개의 도커 데몬)을 사용할 수 있다고 할 수 있는 건가요? 

2. 1번에서 질문드린 상황처럼 N대의 서버가 1개의 도커 데몬을 공통적으로 사용하는 구조가 일반적으로 권장되는 구조인가요?

3. 도커 스웜 모드를 활성화 한다고 하면 1개의 도커 엔진 안에서의 도커 데몬이 1개 -> N개로 늘어나는 건가요?

4. 도커 스웜 모드를 구성하는 '매니저 노드' 와 '워커 노드'는 '도커 데몬'의 일종인 건가요? '매니저, 워커 노드'가 '도커 데몬'에 종속되는 관계인 건지.. 어떤 관계로 구성되는 건지 궁금합니다!(자세한 관계보다는 '도커 데몬' 과 종속되는 관계인지 아닌지와 같은 큰 그림을 알고 싶네요..)

아직 도커 스웜 부분을 다 읽지 않아서.. 책에 나오는 부분인데 제가 중복해서 드리는 질문일 수도 있는데요.. 도커 스웜 개념을 들어가기 전에 나름 기초(?)를 탄탄하게 하고자 하는 목적이라서.. 답변 달아주시면 정말 감사하겠습니다 😀

**Comment by iamcodingcat** [comment]
@alicek106 답변 부탁드립니다!!🙏

**Comment by alicek106** [comment]
안녕하세요, 평일에 시간이 나지 않아 이제야 답변드립니다.

> 서버 N대가 1개의 공통된 도커 엔진을 사용할 수 있는 건가요? ㄴ 저는 그럴 수 있다고 생각하는데요? 배웠다시피 도커 엔진에는 도커 클라이언트/도커 데몬으로 구성되잖아요? 예를 들어, 서버 1,2,3,4가 있고 서버 1에서 도커 데몬이 실행되고 있다고 가정해볼게요. 그러면 서버 2,3,4는 Remote API를 사용해서 서버 1의 도커 데몬과 통신하게 된다면 결국 서버 N대가 1개의 공통된 도커 엔진(엄밀히 말하면 1개의 도커 데몬)을 사용할 수 있다고 할 수 있는 건가요?

- 말씀하신 구조가 가능은 합니다. 다만 도커 스웜 모드는 이러한 구조로 동작하지 않습니다.

> 1번에서 질문드린 상황처럼 N대의 서버가 1개의 도커 데몬을 공통적으로 사용하는 구조가 일반적으로 권장되는 구조인가요?

- 유즈케이스에 따라서 다를 것 같습니다. 애플리케이션이 이러한 구조를 필요로 한다면 가능할 수도 있습니다.

> 도커 스웜 모드를 활성화 한다고 하면 1개의 도커 엔진 안에서의 도커 데몬이 1개 -> N개로 늘어나는 건가요?

- 도커 스웜 모드를 활성화하면 도커 데몬끼리 통신을 주고받습니다. 질문주신 구조는 `서버가 A, B, C, D 4개 존재할 때 A에서는 도커 데몬이 실행되고, B/C/D에서는 A의 도커 데몬에 연결하기 위해 Remote API를 사용하는 구조` 인데요, 이는 도커 스웜 모드가 동작하는 구조와는 다릅니다. 스웜 모드에서 A가 매니저이고 B, C, D가 워커라면 A -> B,C,D 통신 시 도커 데몬에서 management 레벨의 트래픽을 주고 받습니다.

> 도커 스웜 모드를 구성하는 '매니저 노드' 와 '워커 노드'는 '도커 데몬'의 일종인 건가요? '매니저, 워커 노드'가 '도커 데몬'에 종속되는 관계인 건지.. 어떤 관계로 구성되는 건지 궁금합니다!(자세한 관계보다는 '도커 데몬' 과 종속되는 관계인지 아닌지와 같은 큰 그림을 알고 싶네요..)

- 도커 데몬은 매니저 노드일수도, 워커 노드일수도 있습니다. '매니저, 워커 노드'가 '도커 데몬'에 종속된다기보다는, 도커 데몬이 스웜 모드를 사용할 경우 `매니저` 혹은 `워커` 로서의 속성을 갖는다고 이해하시는 편이 더 쉽습니다.

**Comment by iamcodingcat** [comment]
답변 감사합니다! 평일엔 바쁘시군요..저도 질문 올려놓고 주말될때 리마인드 드리도록 하겠습니다! 좋은 밤 되세요~
