### ISSUE TITLE
p319 ClusterIP 서비스 이름으로 요청 시, 내장 DNS Error

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#21]
안녕하세요. 책 319쪽에서 ClusterIP 유형의 서비스를 생성해서 해당 서비스의 이름으로 요청을 테스트 하고 있는데요? 서비스의 IP 로 요청을 하면 응답값이 잘 나오는데, IP 부분을 서비스 이름으로 대신했을 때는 에러가 발생하는데요? 아무래도 쿠버네티스 내장 DNS가 서비스 이름을 IP로 매핑하지 못하는 것 같아요..
```
curl: (6) Could not resolve host: zedd-hostname-svc-clusterip
```
그래서 구글링을 좀 해보니, 내장 DNS 서버가 띄워져 있는 파드가 잘 실행되고 있는지도 보았는데, 잘 실행되고 있더라구요? 
그리고 dnsutils 팟을 생성해서 DNS 서버 체크도 해보았는데, 이것도 잘 동작하고 있더라구요([링크](https://velog.io/@koo8624/Kubernetes-DNS-Error-Temporary-failure-in-name-resolution))

쿠버네티스 설치환경은 책에서 제안해주신 것과 동일한 상태입니다. 

저자 분이 생각하시기에 가능성 있는 원인이 있으실지 문의드립니다!

**Comment by iamcodingcat** [comment]
혹여나 질문을 못보실 것 같아서 멘션 드려요! @alicek106

**Comment by alicek106** [comment]
안녕하세요, 업무가 바빠 늦게나마 답변드립니다.

```
curl: (6) Could not resolve host: zedd-hostname-svc-clusterip
```

이 에러가 발생한 환경이 Pod 내부인지, 호스트 환경인지 알 수 있을까요? 일반적으로 호스트 환경에서는 CoreDNS를 사용하지 않으므로 서비스 이름으로의 resolve는 불가능하지만, 서비스 IP로는 통신이 가능합니다.

**Comment by iamcodingcat** [comment]
@alicek106  아.. 전 호스트 환경에서 테스트를 했습니다. CoreDNS를 사용하는 것은 파드 내부에서 다른 파드랑 통신할 때만 가능했군요.. 이해했습니다! 답변 감사합니다~!
