### ISSUE TITLE
[p.484] QoS 클래스와 메모리 부족

### ISSUE THREAD

**Issue by iamcodingcat** [alicek106/start-docker-kubernetes#22]
@alicek106 
안녕하세요! 저자님의 책으로 이전에 공부하다가 고급 내용을 찾아볼 필요가 있어서 다시 책을 꺼내들은 독자 중 한명입니다. 책 잘 보고 있습니다. 

한 가지 질문이 있어서요. 책 484쪽 [Qos 클래스와 메모리 부족] 이라는 내용의 소제목 문단에서 아래와 같은 내용으로 설명해주셨는데요.

> kubelet이 메모리가 부족한 상황을 감지하면 우선순위가 가장 낮은 파드를 종료한 뒤 다른 노드로 내쫓아내는 퇴거(Evict)를 수행합니다. 만약 메모리 사용량이 갑작스럽게 높아지면 리눅스의 OOM Killer는 OOM 점수가 가장 낮은 컨테이너의 프로세스를 강제로 종료할 수도 있습니다

그런데 헷갈리는 점이 있어요. 일단 QoS가 판단하는 우선순위와 OOM Killer가 계산하는 OOM Score가 어떤지에 따라 강제종료할 프로세스를 선정하는 규칙은 다음과 같다고 이해했습니다.
- QoS가 판단하는 우선순위가 낮다 = 강제로 종료할 프로세스가 될 가능성이 높다
- OOM Killer가 계산한 OOM Score가 높다 = 강제로 종료할 프로세스가 될 가능성이 높다

위 개념을 머리에 두고 언급드린 내용 중 `만약 메모리 사용량이 갑작스럽게 높아지면 리눅스의 OOM Killer는 OOM 점수가 가장 낮은 컨테이너의 프로세스를 강제로 종료할 수도 있습니다` 이 부분이 잘 이해가 가지 않습니다.

일단, 이 때 "메모리 사용량이 갑작스럽게 높아지는" 의 주체는 k8s 노드(서버)인 것이죠? 만약 그렇다면 노드의 메모리 사용량이 높아짐에 따라 리눅스의 OOM Killer는 OOM 점수가 가장 '높은' 컨테아너의 프로세스를 강제 종료해야 하는 것 아닌가요? OOM 점수가 가장 '낮은' 컨테이너의 프로세스를 종료한다는 것은 '그만큼 중요한 프로세스'(ex. kubelet 등..) 라는 것인데, 이러한 중요한 프로세스를 먼저 강제 종료한다라는 게 맞는 건가요? 오히려 OOM 점수가 높은 프로세스를 강제 종료해야 kubelet 과 같은 (OOM 점수가 낮은) 시스템의 핵심 프로세스를 유지해서 시스템 안정화를 확보할 수 있는 것 아닌가요??

혹여나 질문이 이해가 안 가신다면 답글 남겨주세요. 감사합니다!

**Comment by alicek106** [comment]
안녕하세요, 늦게 답변드려 죄송합니다.

글의 의도는 우선순위가 낮은 것을 설명하려 했었던 것 같은데, 지금 다시 읽어보니 `우선순위 점수가 낮은` 이라고 되어 있네요.

지금 읽어봐도 질문자님께서 이해하신 내용이 맞습니다. kubelet이 Memory Pressure를 감지하기 전에 호스트의 메모리 사용량이 급증하게 된다면 리눅스 자체의 OOM killer가 동작해 우선순위 점수가 `높은`, 즉 우선순위가 `낮은` 프로세스가 먼저 종료되는 것이 올바른 설명입니다.

이 부분은 주말에 다시 한 번 검토해보고 원고 교정 작업을 진행하겠습니다. 감사합니다.

**Comment by iamcodingcat** [comment]
@alicek106 
답변 감사합니다! 답변주신 내용 중 마지막에 "우선순위 점수" 라는게 "OOM Score" 의미하는거 맞으시죠?? OOm Score 를 "우선순위 점수" 라고 하니까, QoS 클래스 관점의 "우선순위" 개념이랑 헷갈리네요 ㅎㅎ 

결국, 정리하면 제가 이해한 부분이 맞고, 아래의 개념 정리가 맞는 것이죠!? 한번만 더 더블 체크 부탁드립니다!

만약 호스트의 메모리 사용량이 급증하게 되면,
- 우선순위 점수가 높은 = OOM Score가 높은 = (QoS 클래스의 관점에서의)우선순위가 낮은 프로세스를 먼저 강제 종료한다

**Comment by alicek106** [comment]
네, 이해하신 것이 맞습니다. `우선 순위가 낮다 = OOM Score가 높다` 라서 혼동이 있었던 부분입니다.

다만 실제 운영 환경에서는 상대적으로 빈번하게 발생하는 현상은 아니며, 이런 현상이 발생하지 않도록 적절히 memory limit을 설정해 주는 것이 best practice라 볼 수 있겠습니다.

**Comment by iamcodingcat** [comment]
@alicek106 주말임에도 답변해주셔서 감사합니다! :)
