### ISSUE TITLE
p.42 / 2.2.6.1 호스트 볼륨 공유 / db파일 생성 안돼요!

### ISSUE THREAD

**Issue by maizer2** [alicek106/start-docker-kubernetes#5]
42p에서 db와 wordpress 컨테이너를 각각 생성하여 볼륨을 공유하였습니다.

명령어 작성 후 db 컨테이너에 exec로 접속하여 /home/wordpress_db 폴더를 확인 해 보았는데 존재하지 않습니다.

혹시 공유 디렉토리라 함은 host(사용자) 디렉토리랑 공유된다는 말씀이신가요?

제가 윈도우10 사용중이라 디렉토리 생성 위치를 몰랐던거도 같습니다..

답변부탁드립니다!

**Comment by maizer2** [comment]
해결했습니다. wsl 버전을 2로 올려주세요.

**Comment by alicek106** [comment]
답변드리지 못해 죄송합니다. 회사 일이 너무 바빠서 지금이나마 늦게 답글 달아드립니다.

해결 방법을 공유해주셔서 감사합니다.

**Comment by maizer2** [comment]
아뇨 책 출간해주셔서 너무 감사합니다
좋은 예제 많이 배우고있어요 감사합니다.

2021년 1월 28일 (목) 오후 2:19, Chanho Yong <notifications@github.com>님이 작성:
