### ISSUE TITLE
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - 의 에러

### ISSUE THREAD

**Issue by agj017** [alicek106/start-docker-kubernetes#6]
현재 오픈스택 vm들을 만들어서 쿠버 환경을 구축하려고 합니다.

책 279페이지의 쿠버네티스 저장소 추가 관련 명령어
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - 
실행 했을경우 아래의 에러가 발생합니다.
gpg: no valid OpenPGP data found. 

원인가 해결방안을 알려주세요

**Comment by agj017** [comment]
DNS서버를 설정해서 해결했습니다. ㅜㅜ

**Comment by alicek106** [comment]
답변이 늦어서 죄송합니다 ㅠㅠ 해결하셨다니 다행이네요..
