### ISSUE TITLE
p.35~p.36 / 호스트 IP와 워드프레스 컨테이너 포트로 웹 서버 접근이 안됩니다!

### ISSUE THREAD

**Issue by yeongyeoncho91** [alicek106/start-docker-kubernetes#7]
p.35 의 코드 그대로 데이터베이스, 워드프레스 웹 서버 컨테이너를 생성 및 연동 했는데요.
웹 브라우저로 접근했을 때 화면에 'Error establishing a database connection' 로 노출됩니다.
혹시 mysql 버전을 다르게 하거나 하는 해결 방법이 있을까요? 아님 제가 잘못 작성한 부분이 있을까요? ㅠㅠ
 
<img width="905" alt="스크린샷 2021-05-23 오후 1 38 31" src="https://user-images.githubusercontent.com/18374153/119248572-05819400-bbcd-11eb-82ea-04605dad7498.png">

<img width="848" alt="스크린샷 2021-05-23 오후 1 44 17" src="https://user-images.githubusercontent.com/18374153/119248578-0ca8a200-bbcd-11eb-9ced-9fb2097d06a3.png">

<img width="1200" alt="스크린샷 2021-05-23 오후 1 40 09" src="https://user-images.githubusercontent.com/18374153/119248526-ae7bbf00-bbcc-11eb-9234-5c9ac055e264.png">

**Comment by alicek106** [comment]
안녕하세요.

워드프레스 버전이 올라감에 따라 데이터베이스 호스트 명을 직접 지정해줘야 하도록 변경되었습니다. 최신 증쇄본에서는 수정되어 발행되었지만, 이전 인쇄본이라면 수정되지 않았을 것 같습니다 ^^:

```
# docker run -d \
--name wordpressdb \
-e MYSQL_ROOT_PASSWORD=password \
-e MYSQL_DATABASE=wordpress \
mysql:5.7

docker run -d \
-e WORDPRESS_DB_HOST=mysql \
-e WORDPRESS_DB_USER=root \
-e WORDPRESS_DB_PASSWORD=password \
--name wordpress \
--link wordpressdb:mysql \
-p 80 \
wordpress
```

위 명령어로 실행해보니 문제 없이 잘 동작하는 것을 지금 확인했습니다.
