### ISSUE TITLE
p382 Ingress-example.yaml파일에 대한 질문

### ISSUE THREAD

**Issue by agj017** [alicek106/start-docker-kubernetes#8]
안녕하세요. 책 관련하여 질문 드리겠습니다.

spec.rules.host에 대해서
해당 도메인 이름으로 접근하는 요청에 대해서 처리 규칙을 적용한다. 라고 나와있는데요.
현재 저는 openstack 4개의 노드들 위에 k8s클러스터를 구축하고 있습니다.
ingress를 loadbalancer타입으로 생성하면 오픈스택 cloud provider가 옥타비아(오픈스택에서 제공하는 로드밸런서)를 동적으로 생성할 것이라고 생각합니다.
그러면 이러한 환경에서 dns에 동적으로 도메인이 설정 되어야 된다고 생각되는데 오픈스택 환경에서도 가능 할까요?

**Comment by alicek106** [comment]
안녕하세요. 제가 군대에 다녀오는 바람에 답변이 늦어지게 되었습니다.

제가 지금 당장 오픈스택 환경에서 테스트할수 있는 상황은 아닌지라 정확히 답변드리기는 어렵습니다만, 일반적으로 생각해 보았을 때 오픈스택의 DNS integration이 문제 없이 세팅되었다면 무리 없이 가능할 것으로 생각합니다.

책 내용에서 오픈스택을 다루지 않고 있기도 하고, 무엇보다도 제가 오픈스택에 익숙치 않아 정확한 답변을 드리기 어려운 점 양해 부탁드립니다.
감사합니다.
