### ISSUE TITLE
API Version v1beta1 Ingress 지원 종료

### ISSUE THREAD

**Issue by PARKINHYO** [alicek106/start-docker-kubernetes#9]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

Chapter8 Ingress yaml 파일이 제대로 동작하지 않는 것 같습니다!

![image](https://user-images.githubusercontent.com/47745785/148708180-a5bddcc1-84eb-440c-9509-fba55ca14807.png)

**Comment by alicek106** [comment]
안녕하세요, 제보해주셔서 감사합니다.

PR 제목에서 말씀하신대로, 쿠버네티스 버전이 올라감에 따라 이전 ingress API Version을 지원하지 않는 것으로 보입니다.

해당 내용은 금주 중에 수정하도록 하겠습니다.
감사합니다.
